/* DO NOT EDIT THIS FILE - it is machine generated */
//#include "platform/android/jni/jni.h"
//#include "platform\android\jni\jni.h"
#include "jni.h"
/* Header for class com_example_HelloWorld_HelloWorld */

#ifndef _Included_com_example_HelloWorld_HelloWorld
#define _Included_com_example_HelloWorld_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_HelloWorld_HelloWorld_MODE_PRIVATE
#define com_example_HelloWorld_HelloWorld_MODE_PRIVATE 0L
#undef com_example_HelloWorld_HelloWorld_MODE_WORLD_READABLE
#define com_example_HelloWorld_HelloWorld_MODE_WORLD_READABLE 1L
#undef com_example_HelloWorld_HelloWorld_MODE_WORLD_WRITEABLE
#define com_example_HelloWorld_HelloWorld_MODE_WORLD_WRITEABLE 2L
#undef com_example_HelloWorld_HelloWorld_MODE_APPEND
#define com_example_HelloWorld_HelloWorld_MODE_APPEND 32768L
#undef com_example_HelloWorld_HelloWorld_BIND_AUTO_CREATE
#define com_example_HelloWorld_HelloWorld_BIND_AUTO_CREATE 1L
#undef com_example_HelloWorld_HelloWorld_BIND_DEBUG_UNBIND
#define com_example_HelloWorld_HelloWorld_BIND_DEBUG_UNBIND 2L
#undef com_example_HelloWorld_HelloWorld_BIND_NOT_FOREGROUND
#define com_example_HelloWorld_HelloWorld_BIND_NOT_FOREGROUND 4L
#undef com_example_HelloWorld_HelloWorld_CONTEXT_INCLUDE_CODE
#define com_example_HelloWorld_HelloWorld_CONTEXT_INCLUDE_CODE 1L
#undef com_example_HelloWorld_HelloWorld_CONTEXT_IGNORE_SECURITY
#define com_example_HelloWorld_HelloWorld_CONTEXT_IGNORE_SECURITY 2L
#undef com_example_HelloWorld_HelloWorld_CONTEXT_RESTRICTED
#define com_example_HelloWorld_HelloWorld_CONTEXT_RESTRICTED 4L
#undef com_example_HelloWorld_HelloWorld_RESULT_CANCELED
#define com_example_HelloWorld_HelloWorld_RESULT_CANCELED 0L
#undef com_example_HelloWorld_HelloWorld_RESULT_OK
#define com_example_HelloWorld_HelloWorld_RESULT_OK -1L
#undef com_example_HelloWorld_HelloWorld_RESULT_FIRST_USER
#define com_example_HelloWorld_HelloWorld_RESULT_FIRST_USER 1L
#undef com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_DISABLE
#define com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_DISABLE 0L
#undef com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_DIALER
#define com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_DIALER 1L
#undef com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SHORTCUT
#define com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SHORTCUT 2L
#undef com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SEARCH_LOCAL
#define com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_example_HelloWorld_HelloWorld_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_example_HelloWorld_HelloWorld
 * Method:    loginSuccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_HelloWorld_HelloWorld_loginSuccess
  (JNIEnv *env, jobject obj, jstring str);

/*
 * Class:     com_example_HelloWorld_HelloWorld
 * Method:    paynSuccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_HelloWorld_HelloWorld_paynSuccess
  (JNIEnv *env, jobject obj, jstring str);

/*
 * Class:     com_example_HelloWorld_HelloWorld
 * Method:    payFail 
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_HelloWorld_HelloWorld_payFail
  (JNIEnv * env, jobject obj, jstring str);

#ifdef __cplusplus  
}
#endif
#endif
